### ISSUE TITLE
Fails on Android 10, worked  fine before upgrade to Android 10.

### ISSUE THREAD

**Issue by mike-fabian** [rainerblind/aTrainingTracker#22]
aTrainingTracker worked perfectly for me on my OnePlus6 until a few days ago on Android 9.

Then, a few days ago I got an update to Android 10 (official update from the maker of the phone).
Since then, aTrainingTracker doesn’t work anymore ☹.

![aTrainingTracker-fails-android10](https://user-images.githubusercontent.com/2330175/70522008-94693080-1b40-11ea-8548-5b2827dcf4a3.jpg)
![aTrainingTracker-fails-android10-android-version-information](https://user-images.githubusercontent.com/2330175/70522070-b19dff00-1b40-11ea-9c61-a4b6e16146a6.jpg)

It  still starts tracking  but tracks only a few dots and then it seems to stop. And then it fails saving the files  to SD-card und  uploading them to Strava.

**Comment by rainerblind** [comment]
Hi @mike-fabian, I just published a new release (V4.2.3) that might solve the problem.  Could you please give this version a try?

**Comment by mike-fabian** [comment]
I have 4.2.3 installed now but unfortunately it behaves the same as before. 
It started tracking for a few minutes but then stopped. And the export to SD card and to Strava failed as before.

![atrainingtracker](https://user-images.githubusercontent.com/2330175/71883395-a71e5780-3136-11ea-8176-100717f18ca9.jpg)

**Comment by mike-fabian** [comment]
The changelog in the play store says:

V4.2.3: Bugfix:  Crash of ANT+ Service on  Android  10.

I didn’t try  to  connect to a ANT+ device, I was just using GPS. Not sure whether this  matters.

**Comment by rainerblind** [comment]
Sounds strange.
Do I get it right: The app does not crash but does not track (except for some seconds);
while training, the displayed values are valid.

**Comment by mike-fabian** [comment]
No, it doesn’t seem to crash.

I tried again today: It seems to track until I switch to some other app (I don’t kill atrainingtracker, I just switch to some other app). As soon as I switch to atrainingtracker, it continues tracking.
But I cannot put it into the background, then it stops tracking.

**Comment by mike-fabian** [comment]
You see here that the track has some straight sections, that’s when it stopped tracking because I did switch to some other app. And in the end, the exporting to SD-card and uploading failed, even though I did not switch to another app when stopping the tracking and clicking on "save":

![atrainingtracker](https://user-images.githubusercontent.com/2330175/71987793-2000da80-322f-11ea-987e-a3f7be66d911.jpg)

**Comment by mike-fabian** [comment]
One can see the long straight sections when it stopped tracking because the app was in the background better here:

![atrainingtracker](https://user-images.githubusercontent.com/2330175/71988137-a4ebf400-322f-11ea-9551-47e197a0b745.jpg)

**Comment by rainerblind** [comment]
Looks like the app does not track properly, when it is in the background.
Could you please if the app will get the location all the time: 
![grafik](https://user-images.githubusercontent.com/50083256/72101703-a0096c00-3325-11ea-8d94-74b2ce20aebe.png)

**Comment by mike-fabian** [comment]
This was set to "Allow only while using the app". I don’t know why, I am pretty sure I didn’t set it. 

I’ll go for a walk again tomorrow and see whether it makes a difference.

**Comment by mike-fabian** [comment]
Changing  the permissions to “Allow all the time” did help, now it tracks continuously!

But it still fails saving and uploading to Strava:

![atrainingtracker](https://user-images.githubusercontent.com/2330175/72157673-c62c1c00-33b8-11ea-9e7d-256ea0ec4163.jpg)

**Comment by rainerblind** [comment]
Puh, at least halve of the problem is solved now.
- Getting access to the location when the app is in the background is tracked in issue #28 
- Solving the export problem is  tracked in issue #27

**Comment by mike-fabian** [comment]
Thank you! Then you can probably close this issue here if the rest is tracked in issue #27

**Comment by rainerblind** [comment]
V4.2.5 solves the two problems of this issue.
@mike-fabian could you please confirm.

**Comment by mike-fabian** [comment]
Yes, both problems are fixed for me in V4.2.5.
